# Site settings
title: Seng Lin Shee
description: A personal resume site built with Jekyll Minimal Resume Theme
# baseurl: "" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Seng Lin Shee, PhD
user_description: I currently manage and lead the engineering team in the Innovation Lab at GM Financial. With extensive experience in designing and implementing scalable solutions, I specialize in leveraging Generative AI to drive transformative projects that enhance business value and user experiences. I build high-performing engineering teams from the ground up, scaling them to support strategic goals, mentoring members to foster professional growth, and establishing processes for Proof of Concept initiatives that translate into impactful production deployments.<P/><P/>Outside of my day job, I like to explore, gardening, take photographs/videos and keep fit by collecting awesome finisher medals at organized races.
user_title: Lead, evangelist, architect, developer, tinkerer, explorer...
email: senglin.external<removethis>@kgkoo.com
# twitter_username: lorem_ipsum
instagram_username: 
facebook_username: 
linkedin_username: senglin
github_username:  senglin
medium_username: senglin
twitter_username: slshee
# medium_url: lorem_ipsum.medium.com
# gplus_username:  lorem_ipsum

exclude: ['package.json', 'src', 'node_modules', 'vendor']

